/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.cells.kotlin.openapi.moshi.model

import org.sinou.cells.kotlin.openapi.moshi.model.TreeNode

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param children 
 * @param node 
 */


data class RestTemplateNode (

    @Json(name = "Children")
    val children: kotlin.collections.Map<kotlin.String, TreeNode>? = null,

    @Json(name = "Node")
    val node: TreeNode? = null

) {


}

