/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package org.sinou.cells.kotlin.openapi.moshi.model

import com.squareup.moshi.Json

/**
 * Request to create a selection from a list of nodes.
 *
 * @param nodes
 * @param uuid
 */
data class RestSelection(
    @Json(name = "Nodes") val nodes: kotlin.collections.List<RestNode>,
    @Json(name = "Uuid") val uuid: kotlin.String? = null
) {}
