/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package org.sinou.cells.kotlin.openapi.moshi.model

import com.squareup.moshi.Json

/**
 * @param namespace
 * @param `value`
 */
data class RestJsonMeta(
    @Json(name = "Namespace") val namespace: kotlin.String,
    @Json(name = "Value") val `value`: kotlin.String
) {}
