/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package org.sinou.cells.kotlin.openapi.moshi.model

import com.squareup.moshi.Json

/**
 * @param isLocked
 * @param owner
 */
data class RestLockInfo(
    @Json(name = "IsLocked") val isLocked: kotlin.Boolean? = null,
    @Json(name = "Owner") val owner: kotlin.String? = null
) {}
