/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package org.sinou.cells.kotlin.openapi.moshi.model

import com.squareup.moshi.Json

/** @param propertyValues */
data class RestNamespaceValuesResponse(
    @Json(name = "Values") val propertyValues: kotlin.collections.List<kotlin.String>? = null
) {}
