/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.cells.kotlin.openapi.moshi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.sinou.cells.kotlin.openapi.moshi.model.ActivityOwnerType

class ActivityOwnerTypeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActivityOwnerType
        //val modelInstance = ActivityOwnerType()

    }
}
