/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.cells.kotlin.openapi.moshi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.sinou.cells.kotlin.openapi.moshi.model.RestTemplateNode
import org.sinou.cells.kotlin.openapi.moshi.model.TreeNode

class RestTemplateNodeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RestTemplateNode
        //val modelInstance = RestTemplateNode()

        // to test the property `children`
        should("test children") {
            // uncomment below to test the property
            //modelInstance.children shouldBe ("TODO")
        }

        // to test the property `node`
        should("test node") {
            // uncomment below to test the property
            //modelInstance.node shouldBe ("TODO")
        }

    }
}
