/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package org.sinou.cells.kotlin.openapi.moshi.model

import io.kotlintest.specs.ShouldSpec

class RestBatchUpdateMetaListTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestBatchUpdateMetaList
    // val modelInstance = RestBatchUpdateMetaList()

    // to test the property `updates`
    should("test updates") {
      // uncomment below to test the property
      // modelInstance.updates shouldBe ("TODO")
    }
  }
}
