/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.cells.kotlin.openapi.moshi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.sinou.cells.kotlin.openapi.moshi.model.RestListTemplatesResponse
import org.sinou.cells.kotlin.openapi.moshi.model.RestTemplate

class RestListTemplatesResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RestListTemplatesResponse
        //val modelInstance = RestListTemplatesResponse()

        // to test the property `templates`
        should("test templates") {
            // uncomment below to test the property
            //modelInstance.templates shouldBe ("TODO")
        }

    }
}
